runserver:
	poetry run python manage.py runserver

migrations:
	poetry run python manage.py makemigrations

migrate:
	poetry run python manage.py migrate

pytest:
	poetry run pytest

cov:
	poetry run pytest --cov=places_remember/tests

install:
	poetry install