# Generated by Django 4.2.1 on 2023-05-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember', '0003_memory_lat_memory_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='lng',
        ),
    ]
