# Generated by Django 4.2.1 on 2023-05-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember', '0004_remove_memory_lat_remove_memory_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='date',
        ),
    ]
