# Generated by Django 4.2.1 on 2023-05-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember', '0005_remove_memory_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'verbose_name': 'memory', 'verbose_name_plural': 'memories'},
        ),
        migrations.AddField(
            model_name='memory',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
