# Generated by Django 4.2.1 on 2023-05-29 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember', '0006_alter_memory_options_memory_lat_memory_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='lng',
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('memory_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='places_remember.memory')),
            ],
        ),
    ]
