# Generated by Django 4.2.1 on 2023-05-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember', '0007_remove_memory_lat_remove_memory_lng_coordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinates',
            old_name='memory_id',
            new_name='memory',
        ),
    ]
