# Generated by Django 4.2.1 on 2023-05-29 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember', '0008_rename_memory_id_coordinates_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='memory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='places_remember.memory'),
        ),
    ]
