# Generated by Django 4.2.1 on 2023-06-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember', '0010_memory_lat_memory_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='lng',
        ),
    ]
